package com.moglix.wms.constants;

public enum BatchType {
	SUPPLIER_RETURN, CUSTOMER_RETURN, INBOUND, PACKET_CANCELLED ,SUPPLIER_RETURN_CN, DROPSHIP_RETURN, CUSTOMER_DEBIT_NOTE_RETURN, SUPPLIER_RETURN_DN
}
