package com.moglix.wms.constants;

public enum BatchCSVHeaders {
	BATCH_CODE, REF_NO, BATCH_TYPE, WAREHOUSE_ID, WAREHOUSE_NAME, SUPPLIER_ID, SUPPLIER_NAME, PURCHASE_DATE,
	INBOUNDED_BY, SUPPLIER_PO_ID, SUPPLIER_PO_ITEM_ID, PRODUCT_TYPE, PRODUCT_MSN, PRODUCT_NAME, QUANTITY, UOM,
	PURCHASE_PRICE, TAX_RATE, STORAGE_TYPE, DANGER_TYPE, IS_SERIALIZED, MFG_DATE, EXPIRY_DATE
}
