package com.moglix.wms.constants;

public enum ProductCSVHeaders {
	PRODUCT_MSN, PRODUCT_NAME, BRAND_NAME, UOM, PRODUCT_TYPE, TOTAL_QUANTITY, CURRENT_QUANTITY, STORAGE_TYPE, DANGER_TYPE, SERIALIZED_PRODUCT
}
